namespace Splitio_net_frameworks_tests.Resources
{
    public static class SplitsHelper
    {
        public static string AlwaysOff => "{\"trafficTypeName\":\"user\",\"name\":\"always_off\",\"trafficAllocation\":100,\"trafficAllocationSeed\":-1224384615,\"seed\":-1638900961,\"status\":\"ACTIVE\",\"killed\":false,\"defaultTreatment\":\"off\",\"changeNumber\":1548897742548,\"algo\":2,\"conditions\":[{\"conditionType\":\"ROLLOUT\",\"matcherGroup\":{\"combiner\":\"AND\",\"matchers\":[{\"keySelector\":{\"trafficType\":\"user\",\"attribute\":null},\"matcherType\":\"ALL_KEYS\",\"negate\":false,\"userDefinedSegmentMatcherData\":null,\"whitelistMatcherData\":null,\"unaryNumericMatcherData\":null,\"betweenMatcherData\":null,\"booleanMatcherData\":null,\"dependencyMatcherData\":null,\"stringMatcherData\":null}]},\"partitions\":[{\"treatment\":\"on\",\"size\":0},{\"treatment\":\"off\",\"size\":100}],\"label\":\"default rule\"}]}";
        public static string AlwaysOn => "{\"trafficTypeName\":\"user\",\"name\":\"always_on\",\"trafficAllocation\":100,\"trafficAllocationSeed\":-1953939473,\"seed\":2095087412,\"status\":\"ACTIVE\",\"killed\":false,\"defaultTreatment\":\"off\",\"changeNumber\":1548897724206,\"algo\":2,\"conditions\":[{\"conditionType\":\"ROLLOUT\",\"matcherGroup\":{\"combiner\":\"AND\",\"matchers\":[{\"keySelector\":{\"trafficType\":\"user\",\"attribute\":null},\"matcherType\":\"ALL_KEYS\",\"negate\":false,\"userDefinedSegmentMatcherData\":null,\"whitelistMatcherData\":null,\"unaryNumericMatcherData\":null,\"betweenMatcherData\":null,\"booleanMatcherData\":null,\"dependencyMatcherData\":null,\"stringMatcherData\":null}]},\"partitions\":[{\"treatment\":\"on\",\"size\":100},{\"treatment\":\"off\",\"size\":0}],\"label\":\"default rule\"}]}";
        public static string RandomText => @"Her extensive perceived may any sincerity extremity. Indeed add rather may pretty see. Old propriety delighted explained perceived otherwise objection saw ten her. Doubt merit sir the right these alone keeps. By sometimes intention smallness he northward. Consisted we otherwise arranging commanded discovery it explained. Does cold even song like two yet been. Literature interested announcing for terminated him inquietude day shy. Himself he fertile chicken perhaps waiting if highest no it. Continued promotion has consulted fat improving not way. 
                                            Received shutters expenses ye he pleasant.Drift as blind above at up. No up simple county stairs do should praise as. Drawings sir gay together landlord had law smallest. Formerly welcomed attended declared met say unlocked.Jennings outlived no dwelling denoting in peculiar as he believed. Behaviour excellent middleton be as it curiosity departure ourselves. 
                                            On no twenty spring of in esteem spirit likely estate. Continue new you declared differed learning bringing honoured.At mean mind so upon they rent am walk. Shortly am waiting inhabit smiling he chiefly of in. Lain tore time gone him his dear sure. Fat decisively estimating affronting assistance not. Resolve pursuit regular so calling me. West he plan girl been my then up no.
                                            New the her nor case that lady paid read. Invitation friendship travelling eat everything the out two.Shy you who scarcely expenses debating hastened resolved. Always polite moment on is warmth spirit it to hearts.Downs those still witty an balls so chief so.Moment an little remain no up lively no. Way brought may off our regular country towards adapted cheered. 
                                            Whole every miles as tiled at seven or. Wished he entire esteem mr oh by.Possible bed you pleasure civility boy elegance ham. He prevent request by if in pleased.Picture too and concern has was comfort.Ten difficult resembled eagerness nor.Same park bore on be.Warmth his law design say are person.Pronounce suspected in belonging conveying ye repulsive. 
                                            Was drawing natural fat respect husband. An as noisy an offer drawn blush place. These tried for way joy wrote witty. In mr began music weeks after at begin. Education no dejection so direction pretended household do to.Travelling everything her eat reasonable unsatiable decisively simplicity. Morning request be lasting it fortune demands highest of.
                                            Examine she brother prudent add day ham.Far stairs now coming bed oppose hunted become his.You zealously departure had procuring suspicion. Books whose front would purse if be do decay.Quitting you way formerly disposed perceive ladyship are. Common turned boy direct and yet. 
                                            Literature admiration frequently indulgence announcing are who you her.Was least quick after six.So it yourself repeated together cheerful. Neither it cordial so painful picture studied if. Sex him position doubtful resolved boy expenses.Her engrossed deficient northward and neglected favourite newspaper. But use peculiar produced concerns ten. 
                                            Am if number no up period regard sudden better.Decisively surrounded all admiration and not you.Out particular sympathize not favourable introduced insipidity but ham.Rather number can and set praise. Distrusts an it contented perceived attending oh.Thoroughly estimating introduced stimulated why but motionless.
                                            At ourselves direction believing do he departure. Celebrated her had sentiments understood are projection set. Possession ye no mr unaffected remarkably at.Wrote house in never fruit up.Pasture imagine my garrets an he. However distant she request behaved see nothing.Talking settled at pleased an of me brother weather.";
    }
}
